version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04-scm-browsers
    working_directory: ~/rep
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo apt-get update && sudo apt-get install -y wget python-protobuf
      - run:
          name: Update Git Submodules
          command: git submodule sync && git submodule update --init --recursive
      - run:
          name: Fetch Protobuf `protoc` executable
          command: cd .. && wget https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip && unzip protoc-3.5.1-linux-x86_64.zip -d protoc3 && cd rep
      - run:
          name: Compile Proto File
          command: ../protoc3/bin/protoc -o test.pb source/Zorb.proto
      - run:
          name: Build NanoPB
          command: cd resources/nanopb/generator/proto && make && cd ../../../..
      - run:
          name: Run the Nano PB Generator
          command: python resources/nanopb/generator/nanopb_generator.py test.pb

