/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Wed Jun 13 15:07:37 2018. */

#include "zorb.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t timeline_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, timeline_t, vibrations, vibrations, &vibration_fields),
    PB_LAST_FIELD
};

const pb_field_t vibration_fields[8] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, vibration_t, channels, channels, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, vibration_t, delay, channels, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, vibration_t, duration, delay, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, vibration_t, position, duration, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, vibration_t, start, position, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, vibration_t, end, start, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, vibration_t, easing, end, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(timeline_t, vibrations) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_timeline_vibration)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(timeline_t, vibrations) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_timeline_vibration)
#endif


/* @@protoc_insertion_point(eof) */
